server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/todo_db
    username: todo_user
    password: todo_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true