services:
  db:
    image: mysql:8
    container_name: todo-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: always
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_db
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_pass
    networks:
      - todo-net

volumes:
  db_data:

networks:
  todo-net:
    driver: bridge
